// 아이템 별칭(유저들이 실제로 부르는 이름) 목록 - 검색에서 공식 한글 이름 대신 써도 찾아지게 함.
// 적용: node scripts/apply-item-aliases.js  (items.json의 aliases에 합쳐 넣음, 이미 있는 건 유지)
//
// D2R 한글판은 룬워드·유니크 이름을 번역해서 쓰지만(수수께끼, 요르단의 반지), 커뮤니티에선
// 영어 이름을 소리 나는 대로 읽거나(에니그마, 인피) 줄여서(조던, 호토, CTA) 부르는 경우가 많음

// 키: 아이템 영문 이름(name_en) 정확히. 없는 이름이 있으면 적용 스크립트가 에러를 냄
export const ITEM_ALIASES = {
  // ── 룬워드: 영문 음차 + 흔한 줄임말 ──
  "Ancients' Pledge": ['에이션트 플레지'],
  Authority: ['어쏘리티'],
  Beast: ['비스트'],
  Black: ['블랙'],
  Bone: ['본'],
  Bramble: ['브램블'],
  Brand: ['브랜드'],
  'Breath of the Dying': ['브레스 오브 더 다잉', '브오더', '브레스', 'BOTD'],
  'Call to Arms': ['콜투암즈', '콜투', 'CTA'],
  'Chains of Honor': ['체인 오브 아너', '체오아', '체인', 'COH'],
  Chaos: ['카오스'],
  'Crescent Moon': ['크레센트 문', '크문'],
  Death: ['데스'],
  Delirium: ['딜리리움'],
  Destruction: ['디스트럭션'],
  Doom: ['둠'],
  Dragon: ['드래곤'],
  Dream: ['드림'],
  Duress: ['듀레스'],
  Edge: ['엣지'],
  Enigma: ['에니그마', '에니'],
  Enlightenment: ['인라이튼먼트'],
  Eternity: ['이터니티'],
  Exile: ['엑자일'],
  Faith: ['페이스'],
  Famine: ['페민'],
  'Flickering Flame': ['플리커링 플레임'],
  Fortitude: ['포티튜드', '포티'],
  Fury: ['퓨리'],
  Gloom: ['글룸'],
  Grief: ['그리프'],
  'Hand of Justice': ['핸드 오브 저스티스', '핸오저'],
  Harmony: ['하모니'],
  'Heart of the Oak': ['하트 오브 디 오크', '호토', 'HOTO'],
  'Holy Thunder': ['홀리 썬더'],
  Honor: ['아너'],
  Ice: ['아이스'],
  Infinity: ['인피니티', '인피'],
  Insight: ['인사이트'],
  "King's Grace": ['킹스 그레이스'],
  Kingslayer: ['킹슬레이어'],
  'Last Wish': ['라스트 위시', '라위'],
  Lawbringer: ['로브링어'],
  Leaf: ['리프'],
  Lionheart: ['라이언하트'],
  Lore: ['로어'],
  Malice: ['말리스'],
  Melody: ['멜로디'],
  Memory: ['메모리'],
  Mist: ['미스트'],
  Myth: ['미스'],
  Nadir: ['나디르'],
  Oath: ['오스'],
  Obedience: ['오비디언스'],
  Obsession: ['옵세션'],
  Passion: ['패션'],
  Pattern: ['패턴'],
  Peace: ['피스'],
  'Voice of Reason': ['보이스 오브 리즌'],
  Phoenix: ['피닉스'],
  Plague: ['플레이그'],
  Pride: ['프라이드'],
  Principle: ['프린시플'],
  Prudence: ['프루던스'],
  Radiance: ['래디언스'],
  Rain: ['레인'],
  Rhyme: ['라임'],
  Rift: ['리프트'],
  Sanctuary: ['생츄어리'],
  Silence: ['사일런스'],
  Smoke: ['스모크'],
  Spirit: ['스피릿'],
  Splendor: ['스플렌더'],
  Stealth: ['스텔스'],
  Steel: ['스틸'],
  Stone: ['스톤'],
  Strength: ['스트렝스'],
  Treachery: ['트레처리'],
  'Unbending Will': ['언벤딩 윌'],
  Venom: ['베놈'],
  Void: ['보이드'],
  Wealth: ['웰스'],
  White: ['화이트'],
  Wind: ['윈드'],
  Wisdom: ['위즈덤'],
  Wrath: ['래스'],
  Zephyr: ['제퍼'],
  Hustle: ['허슬'], // 무기·갑옷 두 가지 (게임 내부 이름 Hysteria·Mania)
  Metamorphosis: ['메타모포시스', '메타'],
  Ground: ['그라운드'],
  Temper: ['템퍼'],
  Hearth: ['하스'],
  Cure: ['큐어'],
  Bulwark: ['불워크'],
  Coven: ['코븐'],
  Vigilance: ['비질런스'],
  Ritual: ['리추얼'],

  // ── 유니크: 많이 거래되는 것 위주 ──
  'The Stone of Jordan': ['조던', '조던링'],
  "Mara's Kaleidoscope": ['마라'],
  "Highlord's Wrath": ['하이로드'],
  'Raven Frost': ['레이븐', '레이븐 프로스트'],
  "Bul-Kathos' Wedding Band": ['불카링'],
  Nagelring: ['나겔'],
  'Dwarf Star': ['드워프 스타'],
  'The Cat\'s Eye': ['캣츠아이'],
  "Atma's Scarab": ['아트마'],
  "Seraph's Hymn": ['세라프'],
  'Metalgrid': ['메탈그리드'],
  'War Traveler': ['워트', '워트래블러'],
  'Sandstorm Trek': ['샌드스톰', '샌트'],
  'Gore Rider': ['고어라이더'],
  Waterwalk: ['워터워크'],
  Silkweave: ['실크위브'],
  'Shadow Dancer': ['쉐도우댄서', '섀댄'],
  Marrowwalk: ['마로우워크'],
  'Arachnid Mesh': ['아라크니드'],
  "Verdungo's Hearty Cord": ['버둥고'],
  "Thundergod's Vigor": ['썬더갓', '썬갓'],
  'String of Ears': ['스트링 오브 이어즈', '귀줄'],
  "Nosferatu's Coil": ['노스페라투'],
  Magefist: ['메이지피스트', '메지피'],
  'Chance Guards': ['찬스가드'],
  "Dracul's Grasp": ['드라큘'],
  Steelrend: ['스틸렌드'],
  Frostburn: ['프로스트번'],
  'The Oculus': ['오큘러스', '오큘'],
  "Eschuta's Temper": ['에슈타'],
  "Death's Fathom": ['데스패덤'],
  "Griffon's Eye": ['그리폰'],
  'Crown of Ages': ['크라운 오브 에이지스', '코아'],
  "Andariel's Visage": ['안다리엘', '안다'],
  "Nightwing's Veil": ['나이트윙'],
  "Kira's Guardian": ['키라'],
  'Vampire Gaze': ['뱀파이어 게이즈', '뱀게'],
  'Crown of Thieves': ['크라운 오브 띠브스'],
  'Skin of the Vipermagi': ['바이퍼메기', '바이퍼'],
  Shaftstop: ['샤프트스탑'],
  "Arkaine's Valor": ['아케인'],
  "Templar's Might": ['템플러'],
  "Tyrael's Might": ['티리엘'],
  Leviathan: ['리바이어던'],
  Stormshield: ['스톰실드'],
  'Spirit Ward': ['스피릿 워드'],
  Homunculus: ['호문쿨루스', '호문'],
  'Herald of Zakarum': ['헤럴드 오브 자카룸', '자카룸'],
  "Head Hunter's Glory": ['헤드헌터'],
  Windforce: ['윈드포스', '윈포', 'WF'],
  'Buriza-Do Kyanon': ['부리자'],
  Eaglehorn: ['이글혼'],
  "Lycander's Aim": ['라이칸더'],
  "Titan's Revenge": ['타이탄'],
  Thunderstroke: ['썬더스트로크'],
  "Death's Web": ['데스웹'],
  'The Grandfather': ['그랜드파더', '그랜파'],
  Doombringer: ['둠브링어'],
  Azurewrath: ['아주어래스'],
  Lightsabre: ['라이트세이버'],
  Stormlash: ['스톰래시'],
  "Schaefer's Hammer": ['쉐퍼'],
  Windhammer: ['윈드해머'],
  "Baranar's Star": ['바라나'],
  'Earth Shifter': ['어스시프터'],
  'Ethereal Edge': ['이더리얼 엣지'],
  'Tomb Reaver': ['툼리버'],
  "The Reaper's Toll": ['리퍼스톨'],
  Bonehew: ['본휴'],
  "Arioc's Needle": ['아리옥'],
  Wizardspike: ['위자드스파이크', '위자드'],
  "Jalal's Mane": ['잘랄'],
  "Ormus' Robes": ['오르무스'],
  'Carrion Wind': ['캐리온 윈드'],
  "Saracen's Chance": ['사라센'],
  'Rainbow Facet': ['레인보우 패싯', '레보'],
  "Gheed's Fortune": ['기드'],
  Annihilus: ['애니'],
  'Hellfire Torch': ['토치'],
}

// ── 세트: 세트 이름 별칭을 조각 전부에 (name_en이 이걸로 시작하는 아이템) ──
export const SET_ALIASES = {
  "Tal Rasha's": ['탈라샤', '탈셋'],
  "Immortal King's": ['이모탈킹', '이킹', 'IK'],
  "Trang-Oul's": ['트랑', '트랑울'],
  "Natalya's": ['나탈리아', '나탈'],
  "M'avina's": ['마비나'],
  "Aldur's": ['알더'],
  "Griswold's": ['그리즈월드'],
  "Sigon's": ['시곤'],
  "Tancred's": ['탄크레드'],
  "Isenhart's": ['아이센하트'],
  "Cow King's": ['카우킹'],
  "Naj's": ['나즈'],
  "Sazabi's": ['사자비'],
  "Bul-Kathos'": ['불카토스'],
  "Hwanin's": ['환인'],
}

// ── 룬: 공식 표기와 다르게 흔히 부르는 이름 ──
export const RUNE_ALIASES = {
  'Ber Rune': ['벨'],
  'Ohm Rune': ['옴'],
  'Um Rune': ['움'],
  'Thul Rune': ['툴', '썰'],
  'Amn Rune': ['암'],
}
